#!/usr/bin/env ruby

def sort_and_display(array)
	group = array.group_by { |s| s.date}

	group.each do |k,v|
		puts "Date: " + k
		v.each do |value|
			puts "- " + value.text
		end
	end
end

require 'json'
load 'data.rb'

if File.file?("db")
	file = File.open("db", "rb")
	contents = file.read
	array ||= []

	JSON.parse(contents).each do |e|
		array.push Done.from_json e
	end
end

if ARGV.length == 0
	sort_and_display array
else

	text = ARGV.join(" ")

	t = Done.new(ARGV.join(" "))

	array.push t

	file = File.open("db", "w")
	file.write(JSON.generate array)

end